// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CalculDateJsController from "./calcul_date_js_controller"
application.register("calcul-date-js", CalculDateJsController)
